### ISSUE TITLE
eslint 校验报错,把代码全删了

### ISSUE THREAD

**Issue by yyman001** [vbenjs/vue-vben-admin#1794]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/). 404
- [✓ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [✓ ] 已在 Issues 中搜索了相关的关键词
- [x ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

添加测试辅助功能, 提交到git的时候 eslint 报错,然后新加的代码和文件全部丢失...........真是牛逼
![89822D38AB234E4A2EC1836C3E79B89E](https://user-images.githubusercontent.com/5688485/162707357-a21d3fe0-e273-4970-9b84-5169dd3154ca.png)

### 复现 Bug

提交git, eslint 报错, 全部修改全部丢失

## 系统信息

- 操作系统: win10
- Node 版本: 16.14.2
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm

```cmd
λ pnpm version
{
  npm: '5.1.0',
  ares: '1.18.1',
  brotli: '1.0.9',
  cldr: '40.0',
  icu: '70.1',
  llhttp: '6.0.4',
  modules: '93',
  napi: '8',
  nghttp2: '1.45.1',
  nghttp3: '0.1.0-DEV',
  ngtcp2: '0.1.0-DEV',
  node: '16.14.2',
  openssl: '1.1.1n+quic',
  tz: '2021a3',
  unicode: '14.0',
  uv: '1.43.0',
  v8: '9.4.146.24-node.20',
  zlib: '1.2.11'
}
```

报错信息
```cmd
"C:\Program Files\Git\bin\git.exe" commit -F "C:\work\vue-broker-admin-main\.git\COMMITMESSAGE"

> vben-admin@2.8.0 lint:lint-staged
> lint-staged

[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] package.json — 21 files
[STARTED] *.{js,jsx,ts,tsx} — 11 files
[STARTED] {!(package)*.json,*.code-snippets,.!(browserslist)*rc} — 1 file
[STARTED] package.json — 1 file
[STARTED] *.vue — 5 files
[STARTED] *.{scss,less,styl,html} — 0 file
[STARTED] *.md — 0 file
[SKIPPED] *.{scss,less,styl,html} — no files
[SKIPPED] *.md — no files
[STARTED] eslint --fix
[STARTED] prettier --write--parser json
[STARTED] prettier --write
[STARTED] eslint --fix
[SUCCESS] prettier --write
[SUCCESS] package.json — 1 file
[SUCCESS] prettier --write--parser json
[SUCCESS] {!(package)*.json,*.code-snippets,.!(browserslist)*rc} — 1 file
[FAILED] eslint --fix [FAILED]
[FAILED] eslint --fix [FAILED]
[SUCCESS] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[STARTED] prettier --write
C:\work\vue-broker-admin-main\node_modules\.pnpm\pidtree@0.5.0\node_modules\pidtree\lib\pidtree.js:61
      callback(new Error('No matching pid found'));
               ^

Error: No matching pid found
    at C:\work\vue-broker-admin-main\node_modules\.pnpm\pidtree@0.5.0\node_modules\pidtree\lib\pidtree.js:61:16
    at C:\work\vue-broker-admin-main\node_modules\.pnpm\pidtree@0.5.0\node_modules\pidtree\lib\wmic.js:42:7
    at ChildProcess.<anonymous> (C:\work\vue-broker-admin-main\node_modules\.pnpm\pidtree@0.5.0\node_modules\pidtree\lib\bin.js:45:5)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
husky - pre-commit hook exited with code 1 (error)
Done

Press Enter or Esc to close console...

```
找会代码,想提交都不行, 也关闭不了这个验证

**Comment by tomiaa1926** [comment]
是因为他使用了husky检验代码,删除的代码被保存到git stash了,你可以在提交时git commit -m "xxx" --no-verify 来取消验证,或者直接删除husky也行.不过我也有疑问就是husky检测错误并不提示具体错误在哪里,只是说代码有错误,这种情况是怎么排查代码错误位置的

**Comment by Linjiande** [comment]
我也碰到了，这两天写的代码全部没了，兄弟找到恢复办法了吗

**Comment by tomiaa1926** [comment]
> 

看我回复,他保存到git 的stash 区了 你从stash pop出来就行了

**Comment by Linjiande** [comment]
兄弟，我pop了 但里面还有两个一直pop不出来

**Comment by tomiaa1926** [comment]
> 

那这就属于git 的操作问题了

**Comment by Linjiande** [comment]
好的，万分感谢

**Comment by MySecret** [comment]
我也遇到了，这个怎么解决?难道要把提交前的验证去掉吗

**Comment by yyman001** [comment]
@MySecret 
解决方法:
1. git 提交过滤验证
2. 卸载 husky


卸载:
```cmd
pnpm uninstall husky && git config --unset core.hooksPath
```
husky官网文档
https://typicode.github.io/husky/#/?id=uninstall

**Comment by MySecret** [comment]
> 



> @MySecret 解决方法:
> 
> 1. git 提交过滤验证
> 2. 卸载 husky
> 
> 卸载:
> 
> ```batchfile
> pnpm uninstall husky && git config --unset core.hooksPath
> ```
> 
> husky官网文档 https://typicode.github.io/husky/#/?id=uninstall

如果这样，那git提交前还会对代码做校验吗

**Comment by luchanan** [comment]
把"lint:lint-staged": "lint-staged", 修改为"lint:lint-staged": "lint-staged --no-stash"

**Comment by luchanan** [comment]
可以加上一个参数防止恢复之前的代码，把"lint:lint-staged": "lint-staged", 修改为"lint:lint-staged": "lint-staged --no-stash"。
但是我遇到一问题，就是代码有个变量未使用，我把他修复了，删掉了这个变量，然后commit执行lint-staged的时候eslint --fix它又把改加上去了，请问有解决方法吗？

**Comment by VaCameos** [comment]
删除husky文件夹即可
