### ISSUE TITLE
pnpm serve启动时报错

### ISSUE THREAD

**Issue by LeslieFire** [vbenjs/vue-vben-admin#1868]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
在本地电脑下载最新的代码，在master上顺利安装所有依赖后，执行pnpm serve报错。具体如下：
$ pnpm serve

> vben-admin@2.8.0 serve F:\vue-vben-admin
> npm run dev

> vben-admin@2.8.0 dev F:\vue-vben-admin
> vite

failed to load config from F:\vue-vben-admin\vite.config.ts
error when starting dev server:
F:\vue-vben-admin\node_modules\.pnpm\vite-plugin-html@3.2.0_vite@2.9.5\node_modules\vite-plugin-html\dist\index.cjs:125
      const proxy = viteConfig.server?.proxy ?? {};
 ^（该箭头指向proxy前面的“.”）

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (F:\vue-vben-admin\vite.config.ts:371:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.require.extensions.<computed> [as .ts] (F:\vue-vben-admin\node_modules\.pnpm\vite@2.9.5_less@4.1.2\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:61679:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vben-admin@2.8.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vben-admin@2.8.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
。

### 复现 Bug

git clone 最新代码，master分支，时间是2022年5月1日。
在目录下 pnpm install，安装完成后，执行pnpm serve。

## 系统信息

- 操作系统: Windows 7
- Node 版本: v12.22.12
- 包管理器 (npm/yarn/pnpm) 及其版本:  npm@6.14.16, pnpm@6.0.2

**Comment by BruceHa** [comment]
我也遇到相同问题

**Comment by Benleie** [comment]
俺也是

**Comment by xiongchengzhou** [comment]
我也碰到了,看问题是es特性不支持导致的,可不是知道怎么改啊

**Comment by BruceHa** [comment]
实测 v16.15.0 可以解决该问题

**Comment by xiongchengzhou** [comment]
win7系统只支持nodejs v12以下版本,难道得重装系统才能解决吗

**Comment by BruceHa** [comment]
> win7系统只支持nodejs v12以下版本

大概率得重装了。
