### ISSUE TITLE
yarn dev启动报错

### ISSUE THREAD

**Issue by wanggouzi** [vbenjs/vue-vben-admin#1916]
克隆下来以后用yarn安装了依赖
使用yarn dev启动的时候报下面的错误
failed to load config from xxxxxxx\vbenAdmin\vue-vben-admin\vite.config.ts
error when starting dev server:
TypeError: process$1.homedir is not a function
    at Object.<anonymous> (xxxxxxx\vbenAdmin\vue-vben-admin\node_modules\vite-plugin-mkcert\dist\mkcert.cjs.js:47:50)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (xxxxxxx\vbenAdmin\vue-vben-admin\vite.config.ts:367:41)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.require.extensions.<computed> [as .ts] (xxxxxxx\vbenAdmin\vue-vben-admin\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:61924:20)
error Command failed with exit code 1.
求救！小白不懂为什么

**Comment by sbcdyb123** [comment]
+1

**Comment by sbcdyb123** [comment]
![image](https://user-images.githubusercontent.com/34590929/169631658-0b4c4112-f918-4733-9fa5-591ce1d9c626.png)

**Comment by sbcdyb123** [comment]
我用pnpm安装 然后可以启动，yarn安装就启动不了

**Comment by wanggouzi** [comment]
> 我用pnpm安装 然后可以启动，yarn安装就启动不了

对对对 我看的https://vvbin.cn/doc-next 官方文档用的yarn装的，github是pnpm，不知道yarn装的哪一步出了问题

**Comment by hddlly** [comment]
确实很迷  官方文档用的yarn装的，github是pnpm 跑不起来啊

**Comment by wzxinchen** [comment]
我就直接 yarn，然后一路下来没啥问题

**Comment by wanggouzi** [comment]
> 
我全程用了pnpm就没问题了

**Comment by jareygu** [comment]
是不是node版本问题  要求12.x及以上 且不能是13.x

**Comment by uncarbon97** [comment]
一开始用 2.3.0 二开是还是yarn
现在没有 release 版，直接用 main 分支的话，IDEA 打开项目直接提示用 pnpm 了

是哪次版本改了？

**Comment by yurenzhen** [comment]
这是vite-plugin-mkcert 遇上 vite.config.ts文件里面的server.https: true时, 没有mkcert https证书所导致的问题:

开发测试可以不用改任何代码, 直接在命令行启动参数增加 --https false 即可(你要永久改package.json里面的vite脚本也行), 例如:
yarn dev --https false
pnpm dev --https false
cnpm dev --https false
npm dev --https false
