### ISSUE TITLE
Electron版本编译报错

### ISSUE THREAD

**Issue by slarkerino** [vbenjs/vue-vben-admin#2152]
运行`yarn dev:app`时报如下错误
```
yarn run v1.22.18
$ esno ./build/script/startElectron.ts --env=development --watch
{ _: [], env: 'development', watch: true }
[2022-08-10T02:24:06.882Z] [electron-connect] [server] started electron process: 22080                                                                                                                    10:24:06
[2022-08-10T02:24:06.885Z] [electron-connect] [server] server created and listening on 30080                                                                                                              10:24:06
'undefined' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Error: spawn undefined ENOENT
    at notFoundError (G:\yscloud-admin-electron\node_modules\electron-connect\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (G:\yscloud-admin-electron\node_modules\electron-connect\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (G:\yscloud-admin-electron\node_modules\electron-connect\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (G:\yscloud-admin-electron\node_modules\electron-connect\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn undefined'
}
error Command failed with exit code 1.
info Visit
```

**Comment by slarkerino** [comment]
使用pnpm可以正常运行。官方文档可以更新一下~
