### ISSUE TITLE
mac系统 pnpm启动后报错

### ISSUE THREAD

**Issue by qq13836848** [vbenjs/vue-vben-admin#2199]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

运行报错
ERROR  09:01:13 [vite] error while updating dependencies:                                                                                         09:01:13
Error: EACCES: permission denied, mkdir '/Users/longguo/Documents/jdi/vue-vben-admin/node_modules/.vite/processing'
    at Object.mkdirSync (node:fs:1386:3)
    at runOptimizeDeps (/Users/longguo/Documents/jdi/vue-vben-admin/node_modules/.pnpm/vite@2.9.5_less@4.1.2/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:37257:21)
    at runOptimizer (/Users/longguo/Documents/jdi/vue-vben-admin/node_modules/.pnpm/vite@2.9.5_less@4.1.2/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:58736:44)
    at Timeout.warmUp [as _onTimeout] (/Users/longguo/Documents/jdi/vue-vben-admin/node_modules/.pnpm/vite@2.9.5_less@4.1.2/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:58689:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### 复现 Bug

pnpm install

pnpm run serve

## 系统信息

- 操作系统: macOS 12.4 
- Node 版本: 16.17.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 7.5.1

**Comment by zzzimooo** [comment]
加sudo就好了

**Comment by zsl1549** [comment]
加sudo 也报错

**Comment by zsl1549** [comment]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/32888522/204068446-4a1a6931-7f3b-494f-8a2b-c756abdccfdb.png">

**Comment by miniboom360** [comment]
同样的问题
