### ISSUE TITLE
useModal instance is undefined!

### ISSUE THREAD

**Issue by fanslead** [vbenjs/vue-vben-admin#2518]
```
<template>
  <BasicTable @register="registerTable">
    <template #form-custom> custom-slot </template>
    <template #headerTop>
      <a-alert type="info" show-icon>
        <template #message>
          <template v-if="checkedKeys.length > 0">
            <span>已选中{{ checkedKeys.length }}条记录(可跨页)</span>
            <a-button type="link" @click="checkedKeys = []" size="small">清空</a-button>
          </template>
          <template v-else>
            <span>未选中任何项目</span>
          </template>
        </template>
      </a-alert>
    </template>
    <template #toolbar>
      <a-button type="primary" @click="openModal">新增租户</a-button>
    </template>
    <AddModal @register="register" />
  </BasicTable>
</template>
<script lang="ts">
  import { defineComponent, ref } from 'vue'
  import { BasicColumn, BasicTable, FormProps, useTable } from '/@/components/Table'
  import { Alert } from 'ant-design-vue'
  import { tenantListApi } from '/@/api/admin/tenant'
  import { useModal } from '/@/components/Modal';
  import AddModal from './Modals/AddModal.vue'
  export default defineComponent({
    components: { BasicTable, AddModal, AAlert: Alert },
    setup() {
      const [register, { openModal, setModalProps }] = useModal();
      const checkedKeys = ref<Array<string | number>>([])
      const [registerTable, { getForm }] = useTable({
        title: '租户列表',
        api: tenantListApi,
        columns: getColumns(),
        useSearchForm: true,
        formConfig: getFormConfig(),
        showTableSetting: false,
        tableSetting: { fullScreen: true },
        showIndexColumn: false,
        rowKey: 'id',
        rowSelection: {
          type: 'checkbox',
          selectedRowKeys: checkedKeys,
          onChange: onSelectChange,
        },
      })
      function getFormValues() {
        console.log(getForm().getFieldsValue())
      }
      function onSelectChange(selectedRowKeys: (string | number)[]) {
        // console.log(selectedRowKeys)
        checkedKeys.value = selectedRowKeys
      }

      function getColumns(): BasicColumn[] {
        return [
          {
            title: 'Id',
            dataIndex: 'id',
            fixed: 'left',
            width: 200,
            defaultHidden: true,
          },
          {
            title: '名称',
            dataIndex: 'name',
            fixed: 'left',
            width: 200,
            sorter: true,
          },
        ]
      }
      function getFormConfig(): Partial<FormProps> {
        return {
          labelWidth: 100,
          schemas: [
            {
              field: `filter`,
              label: `租户名`,
              component: 'Input',
              colProps: {
                xl: 12,
                xxl: 8,
              },
            },
          ],
        }
      }
      return {
        register,
        openModal,
        setModalProps,
        registerTable,
        getFormValues,
        checkedKeys,
        onSelectChange,
      }
    },
  })
</script>

```
```
<template>
  <BasicModal v-bind="$attrs" title="新增" :helpMessage="['新增租户']" width="700px">
    <BasicForm
      :labelWidth="100"
      :schemas="schemas"
      :actionColOptions="{ span: 24 }"
      @submit="handleSubmit"
    />
  </BasicModal>
</template>
<script lang="ts">
  import { defineComponent } from 'vue'
  import { BasicModal } from '/@/components/Modal'
  import { BasicForm, FormSchema } from '/@/components/Form'
  import { useMessage } from '/@/hooks/web/useMessage'
  const schemas: FormSchema[] = [
    {
      field: 'name',
      component: 'Input',
      label: '名称',
      colProps: {
        span: 8,
      },
      defaultValue: '',
    },
    {
      field: 'adminEmailAddress',
      component: 'Input',
      label: 'admin邮箱地址',
      colProps: {
        span: 8,
      },
      defaultValue: '',
    },
    {
      field: 'adminPassword',
      component: 'Input',
      label: 'admin密码',
      colProps: {
        span: 8,
      },
      defaultValue: '',
    },
  ]
  export default defineComponent({
    components: { BasicModal, BasicForm },
    setup() {
      const { createMessage } = useMessage()
      return {
        schemas,
        handleSubmit: (values: any) => {
          createMessage.success('click search,values:' + JSON.stringify(values));
        },
      }
    },
  })
</script>

```
runtime-core.esm-bundler.js:218 
 
 Uncaught Error: [Admin error]:useModal instance is undefined!
    at error (log.ts:8:9)
    at getInstance (useModal.ts:60:7)
    at openModal (useModal.ts:79:7)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at emit$1 (runtime-core.esm-bundler.js:720:9)
    at runtime-core.esm-bundler.js:7292:53
    at handleClick2 (button.js:112:7)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)

**Comment by xqh-jason** [comment]
AddModal组件里面是否也有调用register.  <basic-modal @register="register" />

**Comment by fanslead** [comment]
AddModal 的代码上面也发了，没有

**Comment by fanslead** [comment]
请问一下是什么情况？我是照搬demo的代码搞的

**Comment by lucyanddarlin** [comment]
是直接运行就会报错吗，还是访问特定页面的时候

**Comment by fanslead** [comment]
解决了<AddModal @register="register" />不能放在<BasicTable>标签里面，不然会报useModal instance is undefined!

**Comment by kongsiyu** [comment]
@fanslead 
解决了<AddModal @register="register" />不能放在标签里面，不然会报useModal instance is undefined!

这个是什么意思，把AddModal 放在BaseTable之外吗？

**Comment by fanslead** [comment]
> @fanslead 解决了<AddModal @register="register" />不能放在标签里面，不然会报useModal instance is undefined!
> 
> 这个是什么意思，把AddModal 放在BaseTable之外吗？

对的，放在标签外面。

**Comment by lzdml** [comment]
> > @fanslead 解决了<AddModal @register="register" />不能放在标签里面，不然会报useModal instance is undefined!
> > 这个是什么意思，把AddModal 放在BaseTable之外吗？
> 
> 对的，放在标签外面。

你好, 我现在也遇到了这个问题, 并且按照你说的放到最外层是不行的
<img width="890" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/137750167/2646b64a-56aa-436a-9dc9-da594f67369d">
![image](https://github.com/vbenjs/vue-vben-admin/assets/137750167/5daf2c2e-cd29-4c2f-853e-2bd78a684451)
