### ISSUE TITLE
[ERROR] Failed to resolve entry for package "@intlify/shared".

### ISSUE THREAD

**Issue by realtanwei** [vbenjs/vue-vben-admin#3001]
X [ERROR] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package [plugin vite:dep-pre-bundle]

    node_modules/.pnpm/registry.npmmirror.com+esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///D:/Workspaces/WebProjects/PowerDash-Vue/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.9_@types+node@20.4.7_less@4.2.0_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
    at resolvePackageEntry (file:///D:/Workspaces/WebProjects/PowerDash-Vue/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.9_@types+node@20.4.7_less@4.2.0_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
    at tryNodeResolve (file:///D:/Workspaces/WebProjects/PowerDash-Vue/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.9_@types+node@20.4.7_less@4.2.0_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Context.resolveId (file:///D:/Workspaces/WebProjects/PowerDash-Vue/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.9_@types+node@20.4.7_less@4.2.0_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.resolveId (file:///D:/Workspaces/WebProjects/PowerDash-Vue/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.9_@types+node@20.4.7_less@4.2.0_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/Workspaces/WebProjects/PowerDash-Vue/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.9_@types+node@20.4.7_less@4.2.0_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21   
    at async file:///D:/Workspaces/WebProjects/PowerDash-Vue/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.9_@types+node@20.4.7_less@4.2.0_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34   
    at async requestCallbacks.on-resolve (D:\Workspaces\WebProjects\PowerDash-Vue\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1373:22)
    at async handleRequest (D:\Workspaces\WebProjects\PowerDash-Vue\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:729:13)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/registry.npmmirror.com+esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///D:/Workspaces/WebProjects/PowerDash-Vue/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.9_@types+node@20.4.7_less@4.2.0_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19) 
    at handlePlugins (D:\Workspaces\WebProjects\PowerDash-Vue\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1292:21)
    at buildOrContextImpl (D:\Workspaces\WebProjects\PowerDash-Vue\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:978:5)
    at Object.buildOrContext (D:\Workspaces\WebProjects\PowerDash-Vue\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:786:5)
    at D:\Workspaces\WebProjects\PowerDash-Vue\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (D:\Workspaces\WebProjects\PowerDash-Vue\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:2186:27)
    at Object.context (D:\Workspaces\WebProjects\PowerDash-Vue\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///D:/Workspaces/WebProjects/PowerDash-Vue/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.9_@types+node@20.4.7_less@4.2.0_sass@1.66.1/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/.pnpm/registry.npmmirror.com+vue-i18n@9.3.0_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
      8 │ var shared = require('@intlify/shared');
        ╵                      ~~~~~~~~~~~~~~~~~

**Comment by realtanwei** [comment]
有知道是什么原因的吗？

node：v18.17.1
npm：v9.6.7
pnpm：v8.7.4
vite： v4.4.9

**Comment by nick2016** [comment]
have you resolved this problem?

**Comment by search-inner** [comment]
请问是怎么解决的，遇到同样问题了

**Comment by sgknight2020** [comment]
我也遇到这个问题了。
