### ISSUE TITLE
vue-vben-admin-3.0.0-alpha.1 pnpm dev运行报错 

### ISSUE THREAD

**Issue by hhpDevelopment** [vbenjs/vue-vben-admin#3003]
### Describe the bug

pnpm install 报这个
ENOENT: no such file or directory, stat 'D:\vscode_project\vue-vben-admin-3.0.0-alpha.1\node_modules\.pnpm\loader-utils@1.4.2\node_modules\big.js

安装vite后 运行pnpm dev
error when starting dev server:
Error: Cannot find module '@vben/vite-config'
Require stack:
- D:\vscode_project\vue-vben-admin-3.0.0-alpha.1\vite.config.ts
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\vite\dist\node\chunks\dep-df561101.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (D:\vscode_project\vue-vben-admin-3.0.0-alpha.1\vite.config.ts:25:26)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object._require.extensions.<computed> [as .js] (file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/vite/dist/node/chunks/dep-df561101.js:66253:24)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)

npm pnpm 版本
C:\Users\Administrator>npm -v
8.19.4

C:\Users\Administrator>pnpm -v
8.7.4

C:\Users\Administrator>vite -v
vite/4.4.9 win32-x64 node-v16.20.0

> vben-admin@3.0.0-alpha.1 bootstrap D:\vscode_project\vue-vben-admin-3.0.0-alpha.1
> pnpm install

Debugger attached.
Lockfile is up to date, resolution step is skipped
Packages: +1299
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
 ENOENT  ENOENT: no such file or directory, stat 'D:\vscode_project\vue-vben-admin-3.0.0-alpha.1\node_modules\.pnpm\loader-utils@1.4.2\node_modules\big.js'

pnpm: ENOENT: no such file or directory, stat 'D:\vscode_project\vue-vben-admin-3.0.0-alpha.1\node_modules\.pnpm\loader-utils@1.4.2\node_modules\big.js'
Progress: resolved 1299, reused 1007, downloaded 0, added 74
Waiting for the debugger to disconnect...
 ELIFECYCLE  Command failed with exit code 1.
Waiting for the debugger to disconnect...
PS D:\vscode_project\vue-vben-admin-3.0.0-alpha.1> pnpm run dev
Debugger attached.

> vben-admin@3.0.0-alpha.1 dev D:\vscode_project\vue-vben-admin-3.0.0-alpha.1
> pnpm vite

Debugger attached.
Debugger attached.
▲ [WARNING] Cannot find base config file "@vben/ts-config/vue-app.json" [tsconfig.json]

    tsconfig.json:3:13:
      3 │   "extends": "@vben/ts-config/vue-app.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from D:\vscode_project\vue-vben-admin-3.0.0-alpha.1\vite.config.ts
error when starting dev server:
Error: Cannot find module '@vben/vite-config'
Require stack:
- D:\vscode_project\vue-vben-admin-3.0.0-alpha.1\vite.config.ts
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\vite\dist\node\chunks\dep-df561101.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (D:\vscode_project\vue-vben-admin-3.0.0-alpha.1\vite.config.ts:25:26)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object._require.extensions.<computed> [as .js] (file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/vite/dist/node/chunks/dep-df561101.js:66253:24)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
 ELIFECYCLE  Command failed with exit code 1.
Waiting for the debugger to disconnect...

**Comment by likui628** [comment]
把node_modules文件夹删掉，重新pnpm install试一下，没遇到过

**Comment by hhpDevelopment** [comment]
删掉了重新pnpm install还是这样，从2.10版本开始 就一直这样，是不是我少安装了什么环境，现在装了pnpm,vite,还要装其他什么环境吗

**Comment by hhpDevelopment** [comment]
> 把node_modules文件夹删掉，重新pnpm install试一下，没遇到过

删掉了重新pnpm install还是这样，从2.10版本开始 就一直这样，是不是我少安装了什么环境，现在装了pnpm,vite,还要装其他什么环境吗

**Comment by 735448931** [comment]
我也是 该怎么解决

**Comment by 123456hawkins** [comment]
试试更换node版本，我把node版本从20.9.0换到16.20.2就没这个错误了
