### ISSUE TITLE
pnpm build打包后的config.js里的文件title怎么变成数字了，服务端运行报'VITE_GLOB_APP_TITLE' of 't'错误

### ISSUE THREAD

**Issue by Jzow** [vbenjs/vue-vben-admin#3894]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

打包在服务器运行的时候出现错误
```javascript
TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 't' as it is undefined.
    at E5 (index-LnXUB2hu-1717487462909.js:2:148491)
    at b5 (index-LnXUB2hu-1717487462909.js:2:148298)
    at x5 (index-LnXUB2hu-1717487462909.js:2:148381)
    at k5 (index-LnXUB2hu-1717487462909.js:2:171410)
    at index-LnXUB2hu-1717487462909.js:2:171422
```

## 系统信息

- 操作系统: centos
- Node 版本: 20
- pnpm 版本: 9.1.3

相关问题我参考了 #3317 

```javascript
window.__PRODUCTION__00450041004900520050__CONF__={"VITE_GLOB_APP_TITLE":"EAIRP","VITE_GLOB_APP_SHORT_NAME":"WanSen_ERP","VITE_GLOB_API_URL":"/erp-api","VITE_GLOB_API_URL_PREFIX":""};Object.freeze(window.__PRODUCTION__00450041004900520050__CONF__);Object.defineProperty(window,"__PRODUCTION__00450041004900520050__CONF__",{configurable:false,writable:false,});
```

我的.env文件里title内容是`VITE_GLOB_APP_TITLE = EAIRP` 这里注意看到打包后的`_app.config.js`文件里 PRODUCTION里跟着数字了，我一旦把他手动改成EAIRP又可以运行，请问有遇到此问题的同学吗，以前从未遇到过，我的代码跟vben库是同步更新的

**Comment by Jzow** [comment]
奇怪 又可以了
