### ISSUE TITLE
eslint 校验 报 SyntaxError: Unexpected token '||='

### ISSUE THREAD

**Issue by miaobowei** [vbenjs/vue-vben-admin#3931]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
使用Webstorm运行项目,eslint报错
`SyntaxError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.cjs » @vben/eslint-config': Unexpected token '||='
Referenced from: C:\Users\MR\Documents\code\vben\vue-vben-admin\internal\eslint-config\dist\index.cjs

C:\Users\MR\Documents\code\vben\vue-vben-admin\node_modules\.pnpm\@typescript-eslint+scope-manager@7.7.0\node_modules\@typescript-eslint\scope-manager\dist\referencer\ClassVisitor.js:121
        withMethodDecorators ||=
                             ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (C:\Users\MR\Documents\code\vben\vue-vben-admin\node_modules\.pnpm\@typescript-eslint+scope-manager@7.7.0\node_modules\@typescript-eslint\scope-manager\dist\referencer\Referencer.js:20:24)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)`
![image](https://github.com/vbenjs/vue-vben-admin/assets/40782670/e77ac1bb-0483-48cb-b673-fe15ebf8243a)
![image](https://github.com/vbenjs/vue-vben-admin/assets/40782670/a64e2396-cb50-4c28-95c4-bc5de868c3f0)

### 复现 Bug
使用WebStorm运行项目
## 系统信息

- 操作系统: Win10
- Node 版本: 20.11.0
- pnpm 版本: 9.4.0
- WebStorm 版本: 2024.1.5

**Comment by baiseng** [comment]
同问，解决了么？
