### ISSUE TITLE
pnpm install 以后 执行pnpm dev报错

### ISSUE THREAD

**Issue by maxiong1** [vbenjs/vue-vben-admin#4098]
### Version

Vben Admin V5

### Describe the bug?

v5.0.0
v5.0.1
这两个版本执行pnpm dev、pnpm dev:antd、pnpm reinstall 都报错

+ pnpm dev
``` bash
E:\vben3-admin\v5.0.1>pnpm dev

> vben-admin-pro@5.0.1 dev E:\vben3-admin\v5.0.1
> turbo-run dev

node:internal/modules/esm/resolve:264
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'E:\vben3-admin\v5.0.1\scripts\turbo-run\dist\index.mjs' imported from E:\vben3-admin\v5.0.1\scripts\turbo-run\bin\turbo-run.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/esm/translators:158:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:207:14)
    at file:///E:/vben3-admin/v5.0.1/scripts/turbo-run/bin/turbo-run.mjs:3:1 {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///E:/vben3-admin/v5.0.1/scripts/turbo-run/dist/index.mjs'
}

Node.js v20.11.1
```

+ pnpm dev:antd

``` bash
E:\vben3-admin\v5.0.1>pnpm dev:antd

> vben-admin-pro@5.0.1 dev:antd E:\vben3-admin\v5.0.1
> pnpm -F @vben/web-antd run dev


> @vben/web-antd@5.0.1 dev E:\vben3-admin\v5.0.1\apps\web-antd
> pnpm vite --mode development

X [ERROR] Failed to resolve entry for package "@vben/vite-config". The package may have incorrect main/module/exports specified in its package.json. [plugin externalize-deps]

    ../../node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1225:27:
      1225 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///E:/vben3-admin/v5.0.1/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0_sass@1.77.8_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:46351:15)
    at resolvePackageEntry (file:///E:/vben3-admin/v5.0.1/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0_sass@1.77.8_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:46348:3)
    at tryNodeResolve (file:///E:/vben3-admin/v5.0.1/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0_sass@1.77.8_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:46164:16)
    at resolveByViteResolver (file:///E:/vben3-admin/v5.0.1/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0_sass@1.77.8_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:66259:20)
    at file:///E:/vben3-admin/v5.0.1/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0_sass@1.77.8_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:66292:28
    at requestCallbacks.on-resolve (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1225:28)
    at handleRequest (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:647:17)
    at handleIncomingPacket (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:672:7)
    at Socket.readFromStdout (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:518:28)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///E:/vben3-admin/v5.0.1/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0_sass@1.77.8_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:66280:18)
    at handlePlugins (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1150:21)
    at buildOrContextImpl (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:873:5)
    at Object.buildOrContext (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:699:5)
    at E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:2023:15
    at new Promise (<anonymous>)
    at Object.build (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:2022:25)
    at build (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1873:51)
    at bundleConfigFile (file:///E:/vben3-admin/v5.0.1/node_modules/.pnpm/vite@5.3.5_@types+node@22.1.0_sass@1.77.8_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:66235:24)

  The plugin "externalize-deps" was triggered by this import

    vite.config.mts:1:355:
      1 │ ...ta_url = "file:///E:/vben3-admin/v5.0.1/apps/web-antd/vite.config.mts";import { defineConfig } from '@vben/vite-config';
        ╵                                                                                                                 ~~~~~~~~~~~~~~~~~~~

failed to load config from E:\vben3-admin\v5.0.1\apps\web-antd\vite.config.mts
error when starting dev server:
Error: Build failed with 1 error:
../../node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@vben/vite-config". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1472:15)
    at E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:945:25
    at runOnEndCallbacks (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1315:45)
    at buildResponseToResult (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:943:7)
    at E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:970:16
    at responseCallbacks.<computed> (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:622:9)
    at handleIncomingPacket (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:677:12)
    at Socket.readFromStdout (E:\vben3-admin\v5.0.1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
E:\vben3-admin\v5.0.1\apps\web-antd:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vben/web-antd@5.0.1 dev: `pnpm vite --mode development`
Exit status 1
```

+ pnpm reinstall
``` bash
E:\vben3-admin\v5.0.1>pnpm reinstall

> vben-admin-pro@5.0.1 reinstall E:\vben3-admin\v5.0.1
> pnpm clean --del-lock && pnpm bootstrap


> vben-admin-pro@5.0.1 clean E:\vben3-admin\v5.0.1
> vsh clean "--del-lock"

node:internal/modules/esm/resolve:264
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'E:\vben3-admin\v5.0.1\scripts\vsh\dist\index.mjs' imported from E:\vben3-admin\v5.0.1\scripts\vsh\bin\vsh.mjs    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/esm/translators:158:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:207:14)
    at file:///E:/vben3-admin/v5.0.1/scripts/vsh/bin/vsh.mjs:3:1 {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///E:/vben3-admin/v5.0.1/scripts/vsh/dist/index.mjs'
}

Node.js v20.11.1
```

+ pnpm install log

``` bash
.../node_modules/vue-demi postinstall$ node -e "try{require('./scripts/postinstall.js')}catch(e){}"
.../node_modules/vue-demi postinstall: Done

devDependencies:
+ @changesets/changelog-github 0.5.0
+ @changesets/cli 2.27.7
+ @ls-lint/ls-lint 2.2.3
+ @types/jsdom 21.1.7
+ @types/node 22.2.0
+ @vben/commitlint-config 5.0.1 <- internal\lint-configs\commitlint-config
+ @vben/eslint-config 5.0.0 <- internal\lint-configs\eslint-config
+ @vben/prettier-config 5.0.0 <- internal\lint-configs\prettier-config
+ @vben/stylelint-config 5.0.1 <- internal\lint-configs\stylelint-config
+ @vben/tailwind-config 5.0.1 <- internal\tailwind-config
+ @vben/tsconfig 5.0.1 <- internal\tsconfig
+ @vben/turbo-run 5.0.1 <- scripts\turbo-run
+ @vben/vite-config 5.0.1 <- internal\vite-config
+ @vben/vsh 5.0.1 <- scripts\vsh
+ @vue/test-utils 2.4.6
+ autoprefixer 10.4.20
+ cross-env 7.0.3
+ cspell 8.13.2
+ husky 9.1.4
+ is-ci 3.0.1
+ jsdom 24.1.1
+ lint-staged 15.2.8
+ rimraf 6.0.1
+ tailwindcss 3.4.9
+ turbo 2.0.12
+ typescript 5.5.4
+ unbuild 2.0.0
+ vite 5.4.0
+ vitest 2.0.5
+ vue-tsc 2.0.29

. postinstall$ turbo run stub
. postinstall: Failed
 ELIFECYCLE  Command failed with exit code 3221225506.

```

### Reproduction

https://github.com/vbenjs/vue-vben-admin （main分支）

### System Info

```shell
window10、chrome
node v20.11.1
pnpm v9.7.0
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wangjue666** [comment]
@maxiong1  直接执行 `pnpm install` 试试

**Comment by vince292007** [comment]
pnpm install 没执行成功，可以检查 node 版本、pnpm版本是否与项目要求一致

**Comment by anncwb** [comment]
目前的错误上看，是pnpm install没执行成功，提供下 pnpm install 日志看看

**Comment by maxiong1** [comment]
> 目前的错误上看，是pnpm install没执行成功，提供下 pnpm install 日志看看

这样可以吗

``` bash
.../node_modules/vue-demi postinstall$ node -e "try{require('./scripts/postinstall.js')}catch(e){}"
.../node_modules/vue-demi postinstall: Done

devDependencies:
+ @changesets/changelog-github 0.5.0
+ @changesets/cli 2.27.7
+ @ls-lint/ls-lint 2.2.3
+ @types/jsdom 21.1.7
+ @types/node 22.2.0
+ @vben/commitlint-config 5.0.1 <- internal\lint-configs\commitlint-config
+ @vben/eslint-config 5.0.0 <- internal\lint-configs\eslint-config
+ @vben/prettier-config 5.0.0 <- internal\lint-configs\prettier-config
+ @vben/stylelint-config 5.0.1 <- internal\lint-configs\stylelint-config
+ @vben/tailwind-config 5.0.1 <- internal\tailwind-config
+ @vben/tsconfig 5.0.1 <- internal\tsconfig
+ @vben/turbo-run 5.0.1 <- scripts\turbo-run
+ @vben/vite-config 5.0.1 <- internal\vite-config
+ @vben/vsh 5.0.1 <- scripts\vsh
+ @vue/test-utils 2.4.6
+ autoprefixer 10.4.20
+ cross-env 7.0.3
+ cspell 8.13.2
+ husky 9.1.4
+ is-ci 3.0.1
+ jsdom 24.1.1
+ lint-staged 15.2.8
+ rimraf 6.0.1
+ tailwindcss 3.4.9
+ turbo 2.0.12
+ typescript 5.5.4
+ unbuild 2.0.0
+ vite 5.4.0
+ vitest 2.0.5
+ vue-tsc 2.0.29

. postinstall$ turbo run stub
. postinstall: Failed
 ELIFECYCLE  Command failed with exit code 3221225506.
```

**Comment by wangjue666** [comment]
@maxiong1  可以 这时候你再执行 `pnpm dev` 试试

**Comment by maxiong1** [comment]
> @maxiong1 可以 这时候你再执行 `pnpm dev` 试试

试了，还是出现

``` bash
> turbo-run dev

node:internal/modules/esm/resolve:264
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'E:\vue-vben-admin-main\scripts\turbo-run\dist\index.mjs' imported from E:\vue-vben-admin-main\scripts\turbo-run\bin\turbo-run.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/esm/translators:158:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:207:14)
    at file:///E:/vue-vben-admin-main/scripts/turbo-run/bin/turbo-run.mjs:3:1 {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///E:/vue-vben-admin-main/scripts/turbo-run/dist/index.mjs'
}
```

看后面 执行 `postinstall：turbo run stub`  `postinstall：Failed`，是不是还有部分依赖没安装成功? turbo我也全局安装了

**Comment by wangjue666** [comment]
`postinstall: Failed ` 没有执行成功， 你试试再次 `pnpm install `

**Comment by anncwb** [comment]
你用的shell工具事 powershell吗，不是的话换这个试试

**Comment by baiyang9-tal** [comment]
框框报错啊
![Yach_screenshot_20240813201523](https://github.com/user-attachments/assets/55654861-7ce8-4244-96da-3bb10bfeb783)

**Comment by baiyang9-tal** [comment]
一跑起来就是奇奇怪怪的错啊
![Yach_screenshot_20240813201523](https://github.com/user-attachments/assets/ccf730ac-d479-424f-be8d-73db969bbd0f)

**Comment by wangjue666** [comment]
> 一跑起来就是奇奇怪怪的错啊 ![Yach_screenshot_20240813201523](https://private-user-images.githubusercontent.com/101786948/357408056-ccf730ac-d479-424f-be8d-73db969bbd0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTgzNjMsIm5iZiI6MTcyMzU5ODA2MywicGF0aCI6Ii8xMDE3ODY5NDgvMzU3NDA4MDU2LWNjZjczMGFjLWQ0NzktNDI0Zi1iZThkLTczZGI5NjliYmQwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMTE0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOThiNjY4NTI5ZGZlMzUzNjY0ODk0NzRkYzYzZGMzZmFkMmVmZDQwNmVhNTVhODc5NzRjMDQ5ZWFiZTUxYjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3jfWB_RZnOX3t5pKDbz_c7ZMsxjZdU6QIo4yS_ee5gg)

代理关了试试

**Comment by yangtianfu01** [comment]
nodejs的版本, 安装node20.16.0, 不要装22+的版本, pnpm会报错的

**Comment by Luo-RongLi** [comment]
我也遇到这个问题，找了一天资料了，都没解决![微信截图_20240816180222](https://github.com/user-attachments/assets/72468845-8b67-4cf3-90aa-89ca9a47513a)
w
