### ISSUE TITLE
Bug: arm服务器上面如何部署？

### ISSUE THREAD

**Issue by annkoxx** [vbenjs/vue-vben-admin#4333]
### Version

Vben Admin V5

### Describe the bug?

arm服务器上面如何部署？

### Reproduction

arm服务器上面如何部署？

### System Info

```shell
arm服务器上面如何部署？
```

### Relevant log output

```shell
root@instance-20240516-2209:/www/wwwroot/vue-vben-admin# pnpm run dev:ele


> vben-admin-pro@5.2.2 dev:ele /www/wwwroot/vue-vben-admin
> pnpm -F @vben/web-ele run dev


> @vben/web-ele@5.2.2 dev /www/wwwroot/vue-vben-admin/apps/web-ele
> pnpm vite --mode development

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

 ERROR  failed to load config from /www/wwwroot/vue-vben-admin/apps/web-ele/vite.config.mts                                                                                                       18:10:51


 ERROR  error when starting dev server:                                                                                                                                                           18:10:51
Error: /www/wwwroot/vue-vben-admin/node_modules/.pnpm/@ast-grep+napi-linux-arm64-gnu@0.22.6/node_modules/@ast-grep/napi-linux-arm64-gnu/ast-grep-napi.linux-arm64-gnu.node: undefined symbol: static_assert
    at Module._extensions..node (node:internal/modules/cjs/loader:1464:18)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at jiti (/www/wwwroot/vue-vben-admin/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:244799)
    at /www/wwwroot/vue-vben-admin/node_modules/.pnpm/@ast-grep+napi@0.22.6/node_modules/@ast-grep/napi/index.js:219:31
    at evalModule (/www/wwwroot/vue-vben-admin/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
    at jiti (/www/wwwroot/vue-vben-admin/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
    at /www/wwwroot/vue-vben-admin/node_modules/.pnpm/vite-plugin-lib-inject-css@2.1.1_vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.6_/node_modules/vite-plugin-lib-inject-css/dist/index.cjs:39:19

/www/wwwroot/vue-vben-admin/apps/web-ele:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vben/web-ele@5.2.2 dev: `pnpm vite --mode development`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
root@instance-20240516-2209:/www/wwwroot/vue-vben-admin# 
root@instance-20240516-2209:/www/wwwroot/vue-vben-admin# 
root@instance-20240516-2209:/www/wwwroot/vue-vben-admin# 
root@instance-20240516-2209:/www/wwwroot/vue-vben-admin# pnpm remove @ast-grep/napi
 ERR_PNPM_CANNOT_REMOVE_MISSING_DEPS  Cannot remove '@ast-grep/napi': no such dependency found

Available dependencies: @changesets/changelog-github, @changesets/cli, @types/jsdom, @types/node, @vben/commitlint-config, @vben/eslint-config, @vben/prettier-config, @vben/stylelint-config, @vben/tailwind-config, @vben/tsconfig, @vben/turbo-run, @vben/vite-config, @vben/vsh, @vitejs/plugin-vue, @vitejs/plugin-vue-jsx, @vue/test-utils, autoprefixer, cross-env, cspell, husky, is-ci, jsdom, lint-staged, rimraf, tailwindcss, turbo, typescript, unbuild, vite, vitest, vue, vue-tsc
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
没有arm服务器，我这边也不是很清楚，看看有谁能帮忙排查下。
