### ISSUE TITLE
Bug: pnpm build 报错

### ISSUE THREAD

**Issue by fire-men** [vbenjs/vue-vben-admin#4339]
### Version

Vben Admin V5

### Describe the bug?

 ERROR  x Build failed in 2.96s                                                                                                       17:03:28  
[vite]: Rollup failed to resolve import "@vben-core/shared/color" from "D:/Java/code/vue-vben-admin/packages/utils/src/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.6/node_
modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65511:17)
    at onRollupWarning (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.
6/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65543:5)
    at onwarn (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.6/node_mo
dules/vite/dist/node/chunks/dep-BaOMuo4I.js:65206:7)
    at file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:18668:13
    at Object.logger [as onLog] (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-en
try.js:20306:9)
    at ModuleLoader.handleInvalidResolvedId (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/sh
ared/node-entry.js:19257:26)
    at file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19215:26

 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

 ERROR  x Build failed in 2.96s                                                                                                       17:03:28  
[vite]: Rollup failed to resolve import "@vben-core/shared/color" from "D:/Java/code/vue-vben-admin/packages/utils/src/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.6/node_
modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65511:17)
    at onRollupWarning (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.
6/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65543:5)
    at onwarn (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.6/node_mo
dules/vite/dist/node/chunks/dep-BaOMuo4I.js:65206:7)
    at file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:18668:13
    at Object.logger [as onLog] (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-en
try.js:20306:9)
    at ModuleLoader.handleInvalidResolvedId (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/sh
ared/node-entry.js:19257:26)
    at file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19215:26

 ELIFECYCLE  Command failed with exit code 1.

### System Info

```shell
ERROR  x Build failed in 2.96s                                                                                                       17:03:28  
[vite]: Rollup failed to resolve import "@vben-core/shared/color" from "D:/Java/code/vue-vben-admin/packages/utils/src/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.6/node_
modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65511:17)
    at onRollupWarning (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.
6/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65543:5)
    at onwarn (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.31.6/node_mo
dules/vite/dist/node/chunks/dep-BaOMuo4I.js:65206:7)
    at file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:18668:13
    at Object.logger [as onLog] (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-en
try.js:20306:9)
    at ModuleLoader.handleInvalidResolvedId (file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/sh
ared/node-entry.js:19257:26)
    at file:///D:/Java/code/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19215:26

 ELIFECYCLE  Command failed with exit code 1.
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mushu1990** [comment]
+1

**Comment by mushu1990** [comment]
貌似是重新建一个应用test，在应用内执行build的话会抱这个错。但是在大项目内执行了build:test这个应用就可以build成功。然后再返回应用内执行build也就不报错了。奇怪。
