### ISSUE TITLE
Bug: docs build error

### ISSUE THREAD

**Issue by yymjku18** [vbenjs/vue-vben-admin#4361]
### Version

Vben Admin V5

### Describe the bug?

打包文档的时候就会报错，似乎是预览组件`DemoPreview`的路径没有被正确解析，缺了`/`？移除所有使用`DemoPreview`的地方后打包成功。

### Reproduction

![image](https://github.com/user-attachments/assets/0fd0479d-b43a-40c6-b6bb-423c632984fa)

### System Info

```shell
OS: Win11 
Node: v20.17.0
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
报错信息
```
@vben/docs:build:  ERROR  x Build failed in 4.09s
@vben/docs:build:
@vben/docs:build: ✖ building client + server bundles...
@vben/docs:build: 
@vben/docs:build:  ERROR  build error:
@vben/docs:build: [vite-plugin-pwa:build] [vite]: Rollup failed to resolve import "D:Github
ue-vben-admindocssrcdemos
ben-draweasic/index.vue" from "D:/Github/vue-vben-admin/docs/src/components/common-ui/vben-drawer.md".
@vben/docs:build: This is most likely unintended because it can break your application at runtime.
@vben/docs:build: If you do want to externalize this module explicitly add it to
@vben/docs:build: `build.rollupOptions.external`
@vben/docs:build: [vite-plugin-pwa:build] [vite]: Rollup failed to resolve import "D:Github
ue-vben-admindocssrcdemos
ben-draweasic/index.vue" from "D:/Github/vue-vben-admin/docs/src/components/common-ui/vben-drawer.md".
@vben/docs:build: This is most likely unintended because it can break your application at runtime.
@vben/docs:build: If you do want to externalize this module explicitly add it to
@vben/docs:build: `build.rollupOptions.external`
@vben/docs:build:     at viteWarn (file:///D:/Github/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.32.0/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65511:17)
@vben/docs:build:     at onRollupWarning (file:///D:/Github/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.32.0/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65543:5)
@vben/docs:build:     at onwarn (file:///D:/Github/vue-vben-admin/node_modules/.pnpm/vite@5.4.3_@types+node@22.5.4_less@4.2.0_sass@1.78.0_terser@5.32.0/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65206:7)
@vben/docs:build:     at file:///D:/Github/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:18668:13
@vben/docs:build:     at Object.logger [as onLog] (file:///D:/Github/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:20306:9)
@vben/docs:build:     at ModuleLoader.handleInvalidResolvedId (file:///D:/Github/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19257:26)
@vben/docs:build:     at file:///D:/Github/vue-vben-admin/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19215:26
@vben/docs:build:
@vben/docs:build:  ELIFECYCLE  Command failed with exit code 1.
@vben/docs:build: ERROR: command finished with error: command (D:\Github\vue-vben-admin\docs) C:\Users\admin\AppData\Roaming\npm\pnpm.cmd run build exited (1)
@vben/docs#build: command (D:\Github\vue-vben-admin\docs) C:\Users\admin\AppData\Roaming\npm\pnpm.cmd run build exited (1)

```

**Comment by likui628** [comment]
@yymjku18 试一下最新的

**Comment by yymjku18** [comment]
> @yymjku18 试一下最新的

打包成功，非常感谢
