### ISSUE TITLE
Bug: 不能进行打包

### ISSUE THREAD

**Issue by terrinmal** [vbenjs/vue-vben-admin#4760]
### Version

Vben Admin V5

### Describe the bug?

不能进行打包，打包就会报错
Build failed. Please check the error message

 ERROR  error during build:                                                                                                                                  14:58:51  
RollupError: Failed to parse JSON file, invalid JSON syntax found at line 4064
    at error (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Object.error (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25351:20)
    at Object.error (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24472:42)
    at Object.transform (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/dist/node/chunks/dep-b2890f90.js:40372:22)
    at file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25544:40

### Reproduction

运行npm run build
或者npx vite build
 ERROR  error during build:                                                                                                                                  14:58:51  
RollupError: Failed to parse JSON file, invalid JSON syntax found at line 4064
    at error (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Object.error (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25351:20)
    at Object.error (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24472:42)
    at Object.transform (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/dist/node/chunks/dep-b2890f90.js:40372:22)
    at file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25544:40

### System Info

```shell
npm run build
```

### Relevant log output

```shell
ERROR  error during build:                                                                                                                                  14:58:51  
RollupError: Failed to parse JSON file, invalid JSON syntax found at line 4064
    at error (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Object.error (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25351:20)
    at Object.error (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24472:42)
    at Object.transform (file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/dist/node/chunks/dep-b2890f90.js:40372:22)
    at file:///D:/job_create/project_code/02.%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%EF%BC%88%E5%BC%80%E5%8F%91%EF%BC%89/03-%E7%BC%96%E7%A0%81%E9%98%B6%E6%AE%B5/genegle-ui/genegle-pc-admin/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
检查你的代码，你修改到了某个package.json文件
