### ISSUE TITLE
Bug: 点击退出登录时，报pinia相关错误

### ISSUE THREAD

**Issue by elkon028** [vbenjs/vue-vben-admin#4858]
### Version

Vben Admin V5

### Describe the bug?

- apps/web-local/src/views/meeting/libs/store.ts
```js
import { defineStore } from 'pinia'

export type LocalType = {
  // ...
}

export type remotedType = {
  // ...
}

export type PeerType = {
 // ...
}

export type MediaDeviceType = {
  // ...
}

export const useWebRTCStore = defineStore(
  'WebRTCStore',
  () => {
    const moderator = reactive({
      //...
    })

    const local = reactive<LocalType>({
      roomId: '',
      peerId: '',
      peerName: '',
      peerHand: false,
      // features
      useScreen: false,
      useMirror: false,

      isAudioAllowed: false,
      isVideoAllowed: false,
      isScreenAllowed: false,

      isRecording: false,
      isPresenter: false,
      isVideoPrivacyActive: false,

      // local deviceId
      audioDeviceId: '',
      videoDeviceId: '',
      speakerDeviceId: '',
      speakerDisabled: false,

      // video stream config
      videoFps: 30, // 帧率 5 | 15 | 30 | 60
      videoQuality: 'hd', // 'qvga' | 'vga' | 'hd' | 'fhd' | '2k' | '4k' | '6k' | '8k'

      // screen stream config
      screenFps: 30, // 帧率 5 | 15 | 30 | 60
      screenQuality: 'fhd', // 'hd' |'fhd' |'2k' |'4k' |'6k' |'8k'

      // audio config
      autoGainControl: false, // 自动增益控制
      echoCancellation: false, // 回声消除
      noiseSuppression: false, // 降噪
      sampleRate: 48_000, // 采样率 44100 | 48000
      sampleSize: 16, // 采样位数 32 | 16
      channelCount: 2, // 声道数 1 | 2
      micLatencyRange: 50, // 延迟 10 - 1000
      micVolumeRange: 100, // 音量 1 - 100

      audioVolume: 0,
    })

    const mediaDevice = reactive<MediaDeviceType>({
      audio: [],
      video: [],
      speaker: [],

      isEnumerateAudio: false,
      isEnumerateVideo: false,
    })

    const remoted = reactive<Record<string, remotedType>>({})
    const peers = reactive<Record<string, PeerType>>({})

    const localStream = reactive({
      video: new MediaStream(),
      audio: new MediaStream(),
    })

    const isPresenter = ref(false)

    return {
      local,
      peers,
      remoted,
      mediaDevice,
      localStream,
      moderator,
      isPresenter,
    }
  },
  {
    persist: {
      key: 'webrtc',
      storage: localStorage,
      pick: ['local', 'moderator'],
    },
  },
)

```

```js
pinia.js?v=fe989753:1068 Uncaught (in promise) Error: 🍍: Store "WebRTCStore" is built using the setup syntax and does not implement $reset().
    at Proxy.$reset (pinia.js?v=fe989753:1068:13)
    at resetAllStores (setup.ts:41:11)
    at Proxy.logout (auth.ts:76:5)
    at async handleLogout (basic.vue:91:3)
```

### Reproduction

null

### System Info

```shell
all
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
使用Setup Store时，需要自己定义$reset方法来重置state，[文档在此](https://pinia.vuejs.org/zh/core-concepts/state.html#resetting-the-state)。
