### ISSUE TITLE
Bug: pnpm install 出错

### ISSUE THREAD

**Issue by ramus-gif** [vbenjs/vue-vben-admin#5198]
### Version

Vben Admin V5

### Describe the bug?

在拉取后，进行pnpm install时，出现以下信息：
ramus@baoxinniandeMacBook-Pro vue-vben-admin % pnpm install
/opt/homebrew/Cellar/node/23.4.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22379
              throw new UsageError(`This project is configured to use ${result.spec.name} because ${result.target} has a "packageManager" field`);
                    ^

UsageError: This project is configured to use yarn because /Users/ramus/package.json has a "packageManager" field
    at Engine.findProjectSpec (/opt/homebrew/Cellar/node/23.4.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22379:21)
    at async Engine.executePackageManagerRequest (/opt/homebrew/Cellar/node/23.4.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22410:24)
    at async Object.runMain (/opt/homebrew/Cellar/node/23.4.0/lib/node_modules/corepack/dist/lib/corepack.cjs:23102:5) {
  clipanion: { type: 'usage' }
}

### Reproduction

git clone https://github.com/anncwb/vue-vben-admin.git

### System Info

```shell
MAC OS  sonoma 14.3
Node V23.4.0
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
`This project is configured to use yarn because /Users/ramus/package.json has a "packageManager" field`
这个消息告诉你，你的` /Users/ramus/package.json`中配置了`packageManager`，指定了yarn作为包管理器。而本项目需要使用pnpm
